### ISSUE TITLE
There are no precompiled binaries for node 12

### ISSUE THREAD

**Issue by qwloh** [ficristo/brackets-terminal-x#3]
Please upload precompiled binaries for node 12 on windows x64.

` >node-pty-prebuilt@0.7.6 install C:\Users\qiao-wen\AppData\Roaming\Brackets\extensions\brackets-terminal-x-master\node_modules\node-pty-prebuilt`
`> prebuild-install || node scripts/install.js`

`prebuild-install WARN install No prebuilt binaries found (target=12.14.0 runtime=node arch=x64 libc= platform=win32)`

**Comment by ficristo** [comment]
Hi @qwen-3108 
Brackets ships with node version 6. So this extension will not work with node 12.
To install this extension you should use node 6, maybe using nvm-windows to control node versions, or use the drag&drop feature of the Extension Manager of Brackets. In the second case remember to add the `.npmrc` file to your zip.
