### ISSUE TITLE
no visual

### ISSUE THREAD

**Issue by nknandu2406** [ficristo/brackets-terminal-x#4]
terminal is opening but cant see anything. its blank

**Comment by ficristo** [comment]
If you go under "Debug \ Show Developer Tools" what you see?
Have you tried to restart Brackets and see if it does work?
In which way you installed this extension?

In future try to provide more informations about your issue.

**Comment by nknandu2406** [comment]
If i go under "Debug \ Show Developer Tools", I am getting "unable to
create terminal without a connection."
What should i do with this error?
I installed by downloading the zip file and dragged it to brackets to
install.

Thanks for your response.

**Comment by ficristo** [comment]
Are you on Windows? In this case, do you have added the .npmrc file to the zip?
From the error message seems the socket connection of Brackets is blocked, maybe your firewall \ antivirus?
Do you have the same error if you open a new terminal tab?
